version: "3"
services:
  container-app:
    build:
      dockerfile: Dockerfile
      context: ./src
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
    depends_on:
      - mysql

  nextjs-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - container-app

  mysql:
    image: mysql:8.0
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
